name: CI

on:
  push:
  pull_request:

jobs:
  python-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (best-effort)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Compile Python files
        run: |
          python -m py_compile scripts/flight_delays_s3.py

      - name: Parse Airflow DAG (syntax check)
        run: |
          python - << 'PY'
          import ast
          with open('airflow/dags/morningflow_spark.py','r') as f:
              ast.parse(f.read())
          print('DAG parsed OK')
          PY

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Spark job image

      - name: Build Airflow image
